// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

config({
  path: ".env"
});

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx src/infra/prisma/seed.ts",
    //seed: "node dist/src/infra/prisma/seed.js",
  },
  datasource: {
    url: process.env.DATABASE_URL,
  },
});